export const jobCategories = [
  {
    id: 1,
    name: 'Apprentice',
    url: 'apprentice',
    icon: ['fas', 'user-graduate'],
  },
  {
    id: 2,
    name: 'Accounts & Finance',
    url: 'accounts-and-finance',
    icon: ['fas', 'wallet'],
  },
  {
    id: 3,
    name: 'Agriculture',
    url: 'agriculture',
    icon: ['fas', 'seedling'],
  },
  {
    id: 4,
    name: 'Aviation',
    url: 'aviation',
    icon: ['fas', 'fighter-jet'],
  },
  {
    id: 5,
    name: 'Bank',
    url: 'bank',
    icon: ['fas', 'university'],
  },
  {
    id: 6,
    name: 'Clerk',
    url: 'clerk',
    icon: ['fas', 'user-tie'],
  },
  {
    id: 7,
    name: 'Defense',
    url: 'defense',
    icon: ['fas', 'dharmachakra'],
  },
  {
    id: 8,
    name: 'Engineering',
    url: 'engineering',
    icon: ['fas', 'users-cog'],
  },
  {
    id: 9,
    name: 'Faculty & Teaching',
    url: 'faculty-teaching',
    icon: ['fas', 'chalkboard'],
  },
  {
    id: 10,
    name: 'IT & Computer',
    url: 'it-computer',
    icon: ['fas', 'laptop-code'],
  },
  {
    id: 11,
    name: 'Law & Judiciary',
    url: 'law-judiciary',
    icon: ['fas', 'balance-scale'],
  },
  {
    id: 12,
    name: 'Management',
    url: 'management',
    icon: ['fab', 'black-tie'],
  },
  {
    id: 13,
    name: 'Medical & Pharma',
    url: 'medical-pharma',
    icon: ['fas', 'syringe'],
  },
  {
    id: 14,
    name: 'Paramedical',
    url: 'paramedical',
    icon: ['fas', 'user-md'],
  },
  {
    id: 15,
    name: 'Police',
    url: 'police',
    icon: ['fas', 'user-shield'],
  },
  {
    id: 16,
    name: 'Power & Energy',
    url: 'power-energy',
    icon: ['fas', 'bolt'],
  },
  {
    id: 17,
    name: 'Public Sector',
    url: 'public-sector',
    icon: ['fas', 'street-view'],
  },
  {
    id: 18,
    name: 'Railway',
    url: 'railway',
    icon: ['fas', 'train'],
  },
  {
    id: 19,
    name: 'Scientist & Research',
    url: 'scientist-research',
    icon: ['fas', 'satellite'],
  },
  {
    id: 20,
    name: 'SSC & SSSC',
    url: 'ssc-sssc',
    icon: ['fab', 'stripe-s'],
  },
  {
    id: 21,
    name: 'Staff Nurse',
    url: 'staff-nurse',
    icon: ['fas', 'user-nurse'],
  },
  {
    id: 22,
    name: 'Stenographer',
    url: 'stenographer',
    icon: ['fas', 'cash-register'],
  },
  {
    id: 23,
    name: 'Technician',
    url: 'technician',
    icon: ['fas', 'wrench'],
  },
  {
    id: 24,
    name: 'Telecom',
    url: 'telecom',
    icon: ['fas', 'broadcast-tower'],
  },
  {
    id: 25,
    name: 'UPSC & PSC',
    url: 'upsc-psc',
    icon: ['fas', 'underline'],
  },
];
